### ISSUE TITLE
net.links cannot call the topology links!

### ISSUE THREAD

**Issue by cemakpolat** [cgiraldo/mininetRest#1]
Hi, 

Thanks for the rest interface, however, it seems that some functions do not work properly. I want to change myself, but I could not manage retrieving the links data. Do you know how we can fetch them?

Thanks in advance.
Bests
Cem

**Comment by cgiraldo** [comment]
mininetRest uses the python bottle REST framework. If port is not provided, bottle runs by default at port 8080, so if you just run `python demo.py`, the rest url for links should be at:

[http://localhost:8080/links](http://localhost:8080/links)

**Comment by hasanashik** [comment]
I have up Bottle with custom port as 8080 was used by ODL controller. 
mininet_rest.run(host='ip', port=8009, debug=True)
